# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: Elnaril
custom: ["https://www.buymeacoffee.com/elnaril", "https://www.fiverr.com/freelancers/elnaril"]
