name: Tests & Lint

on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'integration_tests/**'
      - 'tests/**'
      - 'uniswap_universal_router_decoder/**'
      - 'mypy.ini'
      - 'pytest.ini'
      - 'tox.ini'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'integration_tests/**'
      - 'tests/**'
      - 'uniswap_universal_router_decoder/**'
      - 'mypy.ini'
      - 'pytest.ini'
      - 'tox.ini'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["all"]

    environment:
      name: Tests

    steps:
    - uses: actions/checkout@v4
    - name: Set up supported Python versions
      uses: actions/setup-python@v5
      with:
        python-version: |
          3.9
          3.10
          3.11
          3.12
          3.13
    - name: Install tox and any other packages
      run: |
        pip install -U pip
        pip install tox
    - name: Run tox
      run: |
        python --version
        tox