name: Tests & Lint

on:
  push:
    paths:
      - '.github/workflows/tests.yml'
      - 'integration_tests/**'
      - 'tests/**'
      - 'uniswap_universal_router_decoder/**'
      - 'mypy.ini'
      - 'pytest.ini'
      - 'tox.ini'
  pull_request:
    paths:
      - '.github/workflows/tests.yml'
      - 'integration_tests/**'
      - 'tests/**'
      - 'uniswap_universal_router_decoder/**'
      - 'mypy.ini'
      - 'pytest.ini'
      - 'tox.ini'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    environment:
      name: Tests

    steps:
    - uses: actions/checkout@v4
    - name: Set up supported Python versions
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Foundry
      run: |
        curl -L https://foundry.paradigm.xyz | bash
        foundryup
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install tox psutil -r requirements_install.txt  # Install tox, psutil, and dev tools
        pip install web3==6.0.0 web3==7.0.0  # Install both web3 versions for matrix
    - name: Run tox
      run: |
        python --version
        tox -e py${{ matrix.python-version | replace('.', '') }}-web3{6,7}  
