name: Tests & Lint

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'integration_tests/**'
      - 'tutorials/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'coverage.json'
      - 'media'
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'integration_tests/**'
      - 'tutorials/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'coverage.json'
      - 'media'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    environment:
      name: Tests

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox and any other packages
      run: pip install tox
    - name: Run tox
      run: |
        export WEB3_HTTP_PROVIDER_URL_ETHEREUM_MAINNET=${{ secrets.WEB3_HTTP_PROVIDER_URL_ETHEREUM_MAINNET }}
        tox
